devices:
  depo:
    s_positions:
      full_down: -238
      full_up: 1
    vol_deg_map:
      0.5: -239
    x_offset: -59
    y_offset: -190
  pH:
    pH_positions:
      full_down: -234
      full_up: 60
    verbose: true
    x_offset: 0
    y_offset: 0
global:
  pi1_address: 192.168.1.11
  pi2_address: 192.168.1.12
stage:
  aux_loc_map:
    acid:
    - -1237
    - -188
    base:
    - -1235
    - -750
    clean:
    - -1058
    - -426
  cell_loc_map: C:\Users\mlowe\OneDrive - Loyola University Maryland\talks\CScapstone_2024_BrendanAudrey\Capstone_Legolas\cell_map.pkl
  home_x_offset: -100
  home_y_offset: -100
